DEBUG: true
SECRET_KEY: 'Django secret key'

EMAIL_HOST: ''
MAIL: ''
HOST_USER: ''
HOST_PASSWORD: ''
EMAIL_PORT: 587
EMAIL_USE_TLS: true
ALLOWED_HOSTS: 
  - 'localhost'

IPFS_CLIENT: 'IPFS client address'

# SCANNER
SCANNER_SLEEP: 10
ORACLE_ADDRESS: ''

SORT_STATUSES:
    recent: '-updated_at'
    cheapest: 'price'
    highest: '-price'

SEARCH_TYPES:
    items: token
    users: user
    collections: collection

SIGNER_ADDRESS: ''
CAPTCHA_SECRET: ''
CAPTCHA_URL: ''
PRIV_KEY: '' #Signer private key
IPFS_DOMAIN: ''

TX_TRACKER_TIMEOUT: 300
RATES_CHECKER_TIMEOUT: 300
CLEAR_TOKEN_TAG_NEW_TIME: 5

TRENDING_TRACKER_TIME: 7 # days

DEFAULT_COMMISSION: 5

API_URL: 'API Url for rates checker'
OPENSEA_API: "https://testnets-api.opensea.io/"

TITLE: 'Project name'
DESCRIPTION: 'Project description'
ITEMS_PER_PAGE: 50 # Default items count on page for pagination

DEFAULT_NETWORK: ethereum

#Initial DB fixtures:
NETWORKS:
  - name: Ethereum #3
    needs_middleware: false
    native_symbol: ETH
    fabric721_address: "0x111222233333444455556666777788889999"
    fabric1155_address: "0x111222233333444455556666777788889999"
    exchange_address: "0x111222233333444455556666777788889999"
    network_type: Ethereum

PROVIDERS:
  - endpoint: "RPC endpoint"
    network: ethereum 

USD_RATES:
  - coin_node: ethereum
    symbol: weth
    name: Wrapped Ethereum
    image: "image url"
    address: "0x111222233333444455556666777788889999"
    decimal: 18
    network: ethereum
    fee_discount: 100

#Celery tasks:
INTERVALS:
  - every: 2
    period: MINUTES
    pk: 1
  - every: 1
    period: HOURS
    pk: 2
  - every: 5
    period: MINUTES
    pk: 3

PERIODIC_TASKS:
  - name: remove_pending
    task: remove_pending
    interval: 2
    enabled: true
  - name: incorrect_bid_checker
    task: incorrect_bid_checker
    interval: 1
    enabled: true
  - name: update_top_users
    task: update_top_users
    interval: 2
    enabled: true
  - name: update_collections_stat_info
    task: update_collection_stat_info
    interval: 3
    enabled: false
  - name: rates_checker
    task: rates_checker
    interval: 3
    enabled: true
  - name: remove_token_tag_new
    task: remove_token_tag_new
    interval: 3
    enabled: true
  - name: transaction_tracker
    task: transaction_tracker
    interval: 3
    enabled: true

MASTER_USER:
    - address: "0x111222233333444455556666777788889999"
      network: ethereum # Network name 
      commission: 3 # User commision

REDIS_HOST: 'test-redis'
REDIS_PORT: 6379
REDIS_EXPIRATION_TIME: 86400 # day in seconds
