EMAIL_HOST: ''
MAIL: ''
HOST_USER: ''
HOST_PASSWORD: ''
EMAIL_PORT: 587
EMAIL_USE_TLS: true
ALLOWED_HOSTS: 
  - ''
  - ''
  - ''

IPFS_CLIENT: '' #IPFS client address

# SCANNER
SCANNER_SLEEP: 10
ORACLE_ADDRESS: ''

SORT_STATUSES:
    recent: '-updated_at'
    cheapest: 'price'
    highest: '-price'

SEARCH_TYPES:
    items: token
    users: user
    collections: collection

SIGNER_ADDRESS: ''
CAPTCHA_SECRET: ''
CAPTCHA_URL: ''
PRIV_KEY: '' #Signer private key

TX_TRACKER_TIMEOUT: 300

REDIS_EXPIRATION_TIME: 86400 # day in seconds
CLEAR_TOKEN_TAG_NEW_TIME: 5

API_URL: '' #API Url for rates checker

TITLE: '' #Project name
DESCRIPTION: '' #Project description
ITEMS_PER_PAGE: 50 #Default items count on page for pagination


#Initial DB fixtures:
NETWORKS:
  - pk: #primary key
    name: #Network name
    needs_middlware: false
    native_symbol: '' #Network symbol
    endpoint: "https:/"
    fabric721_address: "" #Fabric contracts addresses
    fabric1155_address: ""
    exchange_address: ""
    network_type: ""

USD_RATES:
  - coin_node: ''
    symbol: '' #Currency symbol
    name: '' #Currency name
    image: "https://"
    address: ""
    decimal: #Decimal points after 0.
    network: #Network (get by Network's PK) 
    fee_discount: 

MASTER_USER:
  - address: ""
    netwrok: #Network (get by Network's PK) 
    commission: #User commision

#Celery tasks:
INTERVALS: #Intervals for a given task
  - pk: 
    every: #Periodicity (in periods defined bellow)
    period: #MINUTES/HOURS etc
PERIODIC_TASKS:
  - pk: 
    name: '' #Name for a task/function
    task: ''
    interval: #INTERVAL (get by PK)
    enabled: true #Set task to enabled (True is deafult)

REDIS_HOST: 
REDIS_PORT: 

