services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      dds-net:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:8000"
    depends_on:
      - db
    volumes:
      - ./dds/:/code/dds/
      - ./media/:/code/media/
      - ./static/:/code/static/
    networks:
      dds-net:
  rates_checker:
    build:
      context: .
      dockerfile: dockerfiles/rates_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      dds-net:
  scanner_721:
    build:
      context: .
      dockerfile: dockerfiles/scanner_721.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./dds/blocks:/code/blocks
      - ./logs:/code/logs/
    networks:
      dds-net:
  scanner_1155:
    build:
      context: .
      dockerfile: dockerfiles/scanner_1155.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./dds/blocks:/code/blocks
      - ./logs:/code/logs/
    networks:
      dds-net:
  scanner_money:
    build: 
      context: .
      dockerfile: dockerfiles/scanner_money.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes: 
      - ./dds/blocks:/code/blocks
      - ./logs:/code/logs/
    networks:
      dds-net:
networks:
  dds-net:
