services:
  db:
    image: postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      dds2-net:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:8000"
    depends_on:
      - db
    volumes:
      - ./dds/:/code/dds/
      - ./media/:/code/media/
      - ./static/:/code/static/
    networks:
      dds2-net:
  rates_checker:
    build:
      context: .
      dockerfile: dockerfiles/rates_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      dds2-net:
  tx_tracker:
    build:
      context: .
      dockerfile: dockerfiles/tx_tracker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
      dds2-net:
  scanner_721:
    build:
      context: .
      dockerfile: dockerfiles/scanner_721.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./dds/blocks:/code/blocks
      - ./logs:/code/logs/
    networks:
      dds2-net:
  scanner_1155:
    build:
      context: .
      dockerfile: dockerfiles/scanner_1155.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./dds/blocks:/code/blocks
      - ./logs:/code/logs/
    networks:
      dds2-net:
  scanner_money:
    build: 
      context: .
      dockerfile: dockerfiles/scanner_money.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    volumes: 
      - ./dds/blocks:/code/blocks
      - ./logs:/code/logs/
    networks:
      dds2-net:
  redis:
    image: redis:5.0
    restart: unless-stopped
    volumes:
      - ./.docker/redis-data:/data
    networks:
      dds2-net:
  celery_beat:
    build: .
    image: celery:3.1
    command: "celery -A dds beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - redis
    networks:
      dds2-net:
networks:
  dds2-net:
