from django.urls import path

from src.store.views import (
    AuctionEndView,
    BuyTokenView,
    CollectionImportView,
    CreateCollectionView,
    CreateView,
    GetCollectionByAdressView,
    GetCollectionView,
    GetHotCollectionsView,
    GetHotView,
    GetLikedView,
    GetMostBiddedView,
    GetRelatedView,
    GetView,
    MakeBid,
    NotableDropView,
    RemoveRejectView,
    ReportView,
    SearchView,
    SetCoverView,
    SupportView,
    TokenBurnView,
    TransactionTrackerView,
    TransferOwned,
    VerificateBetView,
    get_bids,
    get_favorites,
    get_fee,
    get_hot_bids,
    get_max_price,
    get_random_token,
    get_tags,
    get_total_count,
    trending_collections,
)

urlpatterns = [
    path("create_token/", CreateView.as_view()),
    path("create_collection/", CreateCollectionView.as_view()),
    path("most_bidded/", GetMostBiddedView.as_view()),
    path("related/<int:id>/", GetRelatedView.as_view()),
    path("track_transaction/", TransactionTrackerView.as_view()),
    path("hot/", GetHotView.as_view()),
    path("hot_collections/", GetHotCollectionsView.as_view()),
    path("search/", SearchView.as_view()),
    path("liked/<str:user_id>/", GetLikedView.as_view()),
    path("transfer/<str:token>/", TransferOwned.as_view()),
    path("collection/<str:param>/", GetCollectionView.as_view()),
    path("buy/", BuyTokenView.as_view()),
    path("tags/", get_tags),
    path("max_price/", get_max_price),
    path("bids/make_bid/", MakeBid.as_view()),
    path("get_bids/<int:token_id>/", get_bids),
    path("hot_bids/", get_hot_bids),
    path("verificate_bet/<int:token_id>/", VerificateBetView.as_view()),
    path("end_auction/<int:token_id>/", AuctionEndView.as_view()),
    path("report/", ReportView.as_view()),
    path("set_cover/", SetCoverView.as_view()),
    path("fee/", get_fee),
    path("favorites/", get_favorites),
    path("get_random_token/", get_random_token),
    path("support/", SupportView.as_view()),
    path("metadata/<str:address>/", GetCollectionByAdressView.as_view()),
    path("remove-reject/", RemoveRejectView.as_view()),
    path("collection-import/", CollectionImportView.as_view()),
    path("get_total_count/", get_total_count),
    path("trending_collections/", trending_collections),
    path("<int:id>/", GetView.as_view()),
    path("<int:token_id>/burn/", TokenBurnView.as_view()),
    path("drops/", NotableDropView.as_view()),
]
