# Generated by Django 3.1.7 on 2021-07-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='media',
        ),
        migrations.AddField(
            model_name='token',
            name='ipfs',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
