# Generated by Django 3.1.7 on 2021-06-09 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(choices=[('like', 'like'), ('follow', 'follow')], default='follow', max_length=6)),
                ('token', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('whom_follow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TokenHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('Transfer', 'Transfer'), ('Buy', 'Buy'), ('Mint', 'Mint'), ('Burn', 'Burn')], default='Transfer', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=78, null=True)),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_owner', to=settings.AUTH_USER_MODEL)),
                ('old_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_owner', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.token')),
            ],
        ),
        migrations.CreateModel(
            name='ListingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=78, null=True)),
                ('method', models.CharField(choices=[('Listing', 'Listing')], default='Listing', max_length=7)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=78, null=True)),
                ('method', models.CharField(choices=[('Bet', 'Bet')], default='Bet', max_length=3)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='useraction',
            constraint=models.UniqueConstraint(fields=('whom_follow', 'user'), name='unique_followers'),
        ),
        migrations.AddConstraint(
            model_name='useraction',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique_likes'),
        ),
    ]
